-- MySQL Script generated by MySQL Workbench
-- Tue Jun  6 15:00:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Barbearia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Barbearia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Barbearia` DEFAULT CHARACTER SET utf8 ;
USE `Barbearia` ;

-- -----------------------------------------------------
-- Table `Barbearia`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `senha_cliente` VARCHAR(100) NULL,
  `telefone` INT NULL,
  `cpf` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Barbearia`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(100) NULL,
  `cargo` VARCHAR(100) NULL,
  `salario` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Barbearia`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_servico` VARCHAR(100) NULL,
  `preco` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Barbearia`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`agendamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_agendamento` DATE NULL,
  `hora_agendamento` TIME NULL,
  `clientes_id` INT NOT NULL,
  `funcionario_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agendamento_clientes_idx` (`clientes_id` ASC) ,
  INDEX `fk_agendamento_funcionario1_idx` (`funcionario_id` ASC) ,
  INDEX `fk_agendamento_servico1_idx` (`servico_id` ASC) ,
  CONSTRAINT `fk_agendamento_clientes`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `Barbearia`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamento_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `Barbearia`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamento_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `Barbearia`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Barbearia`.`gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`gerente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_gerente` VARCHAR(100) NULL,
  `senha_gerente` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Barbearia`.`servico_realizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`servico_realizado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `agendamento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_servico_realizado_agendamento1_idx` (`agendamento_id` ASC) ,
  CONSTRAINT `fk_servico_realizado_agendamento1`
    FOREIGN KEY (`agendamento_id`)
    REFERENCES `Barbearia`.`agendamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Barbearia`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Barbearia`.`pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_hora_pagamento` DATETIME NULL,
  `valor` FLOAT NULL,
  `metodo_pagamento` VARCHAR(100) NULL,
  `servico_realizado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagamento_servico_realizado1_idx` (`servico_realizado_id` ASC) ,
  CONSTRAINT `fk_pagamento_servico_realizado1`
    FOREIGN KEY (`servico_realizado_id`)
    REFERENCES `Barbearia`.`servico_realizado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
